output_dir: './outputs_shared_backbone'

# Shared backbone model configuration
model:
  type: 'shared_lora'  # Use shared backbone with LoRA
  model_name: 'Rostlab/prot_bert_bfd'
  readout: 'pooler'
  freeze_bert: true
  lora_rank: 16
  lora_alpha: 32
  lora_dropout: 0.1

# Multi-task datasets
datasets:
  - type: 'Thermostability'
    path: './data'
    split: 'human_cell'
    center: true  # Primary task

  - type: 'SecondaryStructure'
    path: './data'
    center: false  # Auxiliary task

# Task configurations (must match datasets order)
tasks:
  - type: 'regression'      # Thermostability
    num_labels: 1
    loss: 'mse'

  - type: 'token_classification'  # Secondary Structure  
    num_labels: 8
    loss: 'cross_entropy'

# Training settings
train:
  num_epoch: 1              # Single epoch for quick test
  batch_size: 8             # Adjust based on your GPU
  gradient_interval: 1
  tradeoff: 0.5             # Weight for auxiliary tasks

# Optimizer
optimizer:
  type: 'AdamW'
  lr: 2e-5
  weight_decay: 0.01

# Optional scheduler
scheduler:
  type: 'StepLR'
  step_size: 3
  gamma: 0.5

# Engine settings
engine:
  batch_size: 8
  num_worker: 2           # Increase if you have more CPU cores
  log_interval: 50        # Log every 50 batches

eval_metric: 'accuracy'