datasets:
- center: true
  path: ./data
  type: SecondaryStructure
- center: false
  path: ./data
  type: Thermostability
- center: false
  path: ./data
  type: PeptideHLAMHCAffinity
engine:
  batch_size: 4
  log_interval: 10
  num_worker: 0
eval_metric: accuracy
model:
  freeze_bert: true
  lora_alpha: 16
  lora_dropout: 0.1
  lora_rank: 8
  model_name: Rostlab/prot_bert_bfd
  readout: pooler
  type: lora
optimizer:
  lr: 2.0e-05
  type: AdamW
  weight_decay: 0.01
output_dir: ./quick_start_outputs
tasks:
- loss: cross_entropy
  num_labels: 8
  type: token_classification
- loss: mse
  num_labels: 1
  type: regression
- loss: mse
  num_labels: 1
  type: regression
train:
  batch_size: 4
  gradient_interval: 2
  num_epoch: 2
  tradeoff: 0.5
